openapi: 3.1.0
info:
  title: Fallback Experience API
  version: 1.0.0
  description: API for setting up, reading, and authenticating fallback access codes.
servers:
  - url: https://api.example.com
    description: Production

tags:
  - name: Fallback Experience

paths:
  /fallback-experience/setup:
    post:
      tags: [Fallback Experience]
      summary: Setup code
      description: Creates or updates the fallback code and returns identifiers.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                enabled:
                  type: boolean
              required: [enabled]
      responses:
        '201':
          description: Code created or updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_identifier:
                    type: string
                    pattern: '^[0-9]{12}$'
                    example: '123456789012'
                  pin:
                    type: string
                    pattern: '^[0-9]{6}$'
                    example: '042913'
                required: [account_identifier, pin]
        '400':
          $ref: '#/components/responses/BadRequest'
        '429':
          $ref: '#/components/responses/RateLimited'
        '500':
          $ref: '#/components/responses/ServerError'

  /fallback-experience/read:
    post:
      tags: [Fallback Experience]
      summary: Read account identifier from code
      description: Receives a code and returns the associated `account_identifier`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pin:
                  type: string
                  pattern: '^[0-9]{6}$'
              required: [pin]
      responses:
        '200':
          description: Account identifier found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_identifier:
                    type: string
                    pattern: '^[0-9]{12}$'
                required: [account_identifier]
        '403':
          description: Invalid code.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/RateLimited'
        '500':
          $ref: '#/components/responses/ServerError'

  /fallback-experience/authenticate:
    post:
      tags: [Fallback Experience]
      summary: Authenticate code
      description: Validates an `account_identifier` + code pair.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_identifier:
                  type: string
                  pattern: '^[0-9]{12}$'
                pin:
                  type: string
                  pattern: '^[0-9]{6}$'
              required: [account_identifier, pin]
      responses:
        '200':
          description: Valid code.
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    example: true
                required: [valid]
        '403':
          description: Invalid code or account identifier.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/RateLimited'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  responses:
    BadRequest:
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    RateLimited:
      description: Too many requests.
      headers:
        Retry-After:
          schema:
            type: integer
            description: Seconds until retry.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          example: INVALID_CODE
        message:
          type: string
          example: The provided code or account identifier is invalid.
      required: [code, message]
