openapi: 3.0.3
info:
  title: Fallback Experience API
  version: 1.0.0
  description: |
    API for setting up, reading, and authenticating fallback access codes.
    - All the operations are registered with audit logs for tracking.
    - The PIN is never stored in plain text. It will be stored in a hashed form using a FIPS-compliant library and algorithm.
servers:
  - url: https://api.talkdeskstg.com
    description: Staging

tags:
  - name: Fallback Experience


paths:
  /fallback-experience/setup:
    post:
      tags: [Fallback Experience]
      summary: Setup code
      security:
        - oauth2:
            - fallback:write
      description: Creates or updates the fallback code and returns identifiers.
      responses:
        '201':
          description: Code created or updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_identifier:
                    type: string
                    pattern: '^[0-9]{12}$'
                    example: '123456789012'
                  pin:
                    type: string
                    pattern: '^[0-9]{6}$'
                    example: '042913'
                required: [account_identifier, pin]
        '401':
          description: Missing or invalid access token, or token lacks required scope (fallback:write).
        '400':
          description: Invalid request body or parameters.
        '429':
          description: Too many requests.
        '500':
          description: Internal server error.
    delete:
      tags: [Fallback Experience]
      summary: Disable codes
      security:
        - oauth2:
            - "fallback:write"
      description: Disables (deletes) the fallback codes.
      responses:
        '204':
          description: Codes disabled.
        '401':
          description: Missing or invalid access token, or token lacks required scope (fallback:write).
        '404':
          description: No fallback codes configured.
        '429':
          description: Too many requests.
        '500':
          description: Internal server error.

  /fallback-experience/read:
    post:
      tags: [Fallback Experience]
      summary: Returns the `account_identifier`
      security:
        - oauth2:
            - fallback:read
      description: Returns the `account_identifier`.
      responses:
        '200':
          description: Account identifier found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_identifier:
                    type: string
                    pattern: '^[0-9]{12}$'
                required: [account_identifier]
        '401':
          description: Missing or invalid access token, or token lacks required scope (fallback:read).
        '404':
          description: Account identifier not found.
        '429':
          description: Too many requests.
        '500':
          description: Internal server error.

  /fallback-experience/authenticate:
    post:
      tags: [Fallback Experience]
      summary: Authenticate codes
      security:
        - oauth2:
            - fallback:read
      description: Validates an `account_identifier` + `pin` code pair.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_identifier:
                  type: string
                  pattern: '^[0-9]{12}$'
                pin:
                  type: string
                  pattern: '^[0-9]{6}$'
              required: [account_identifier, pin]
      responses:
        '200':
          description: Valid codes.
        '401':
          description: Missing or invalid access token, or token lacks required scope (fallback:read).
        '403':
          description: Invalid pin code or account identifier.
        '404':
          description: Account identifier not found.
        '429':
          description: Too many requests.
        '500':
          description: Internal server error.

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://account.talkdeskstgid.com/oauth/token"
          scopes:
            fallback:read: "Read fallback configuration and validate codes"
            fallback:write: "Create or update fallback codes"
